com:
  sse:
    xubf:
      proj:
        path: C:\\workspace



spring:
  datasource:
    url: jdbc:mysql://localhost:12345/proj_mgnt
    username: root
    password: 12345

mybatis:
  mapperLocations: classpath:/mapper/**/*.xml
